In [5]:
L = list(range(10))
print(L)
print([type(item) for item in L])

 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]


In [1]:
import numpy as np
print(np.__version__)
print(np.zeros(10, dtype='int'))
print(np.ones(5, dtype='float'))
print(np.full((3,3), 1.23))


1.26.3
[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1.]
[[1.23 1.23 1.23]
 [1.23 1.23 1.23]
 [1.23 1.23 1.23]]


In [2]:
import numpy as np
print(np.arange(0, 20, 2))

print(np.linspace(0,1,5))
print(np.linspace(0,10,3))
# Generate a sequence of numbers from 0 to 9 with step size of 

print(np.eye(3))
print(np.eye(2))
 

[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[ 0.  5. 10.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [3]:
import numpy as np
x  = np.array([1,2,3,4,5,67,8,9])
print(x )# full array
print(x[0]) # first index
print(x[-1]) # last index
print(x[5])  # fifth index
print(x[-3]) # third last index

[ 1  2  3  4  5 67  8  9]
1
9
67
67


In [4]:
x2 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(x2)
print(x2[0,0]) #first row first column
print(x2[1,2]) # second row third column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6


In [6]:
x = np.arange(10)
print(x)
print(x[:5])  #end with 4th position
print(x[4:]) # start with  5th position
print(x[:] ) #whole array
print(x[2:5]) #from 3nd to  5th positions 
print(x[::2]) #return  every second element from the list starting from index 0 (default).
print(x[1::2]) 
print(x[::-1]) # reverse an array


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [23]:
x1 = np.array([[1,2,3],[4,6,8],[7,8,9]])
x2 = np.array([[4,5,6],[8,9,0,]])
print(np.concatenate([x1,x1]))
grid  = np.array([12,3,4])
grid = np.array([87,0,5])
print(np.concatenate([grid, grid]))
print(np.vstack([grid, x2]))
grid = np.array([[9],[9]])
print(np.hstack([grid, grid]))

[[1 2 3]
 [4 6 8]
 [7 8 9]
 [1 2 3]
 [4 6 8]
 [7 8 9]]
[87  0  5 87  0  5]
[[87  0  5]
 [ 4  5  6]
 [ 8  9  0]]
[[9 9]
 [9 9]]


In [27]:
x = np.arange(20)
print(x)
x1, x2, x3 = np.split(x,[3,9])
print(x1,x2, x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2] [3 4 5 6 7 8] [ 9 10 11 12 13 14 15 16 17 18 19]


In [34]:
grid = np.arange(6).reshape((2,3)) # 2 row and 3 column 
print(grid)
grid = np.arange(18).reshape((6,3))  # 6 row and  3 column matrix
print(grid)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [35]:
u , l = np.vsplit(grid,[2])
print(u , l)

[[0 1 2]
 [3 4 5]] [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
